---
- name: Create a new user
  ansible.builtin.user:
    name: "{{ new_user_username }}"
    password: "{{ new_user_password }}"
    groups: sudo
    shell: /bin/bash
    generate_ssh_key: true
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    append: true
    state: present

- name: Syncronize authorized_keys
  ansible.builtin.copy:
    src: ~/.ssh/authorized_keys
    dest: /home/{{ new_user_username }}/.ssh/authorized_keys
    owner: "{{ new_user_username }}"
    group: "{{ new_user_username }}"
    mode: '0400'
