---
- name: Ensure authentication file is set
  ansible.builtin.lineinfile:
    path: /etc/openvpn/vpn.conf
    regexp: '^auth-user-pass'
    line: 'auth-user-pass auth.txt'
    state: present

- name: Ensure openvpn script security level
  ansible.builtin.lineinfile:
    path: /etc/openvpn/vpn.conf
    line: 'script-security 2'
    insertafter: 'auth-user-pass auth.txt'
    state: present

- name: Ensure openvpn reloads /etc/resolve.conf on tun0 up
  ansible.builtin.lineinfile:
    path: /etc/openvpn/vpn.conf
    line: 'up /etc/openvpn/update-resolv-conf'
    insertafter: 'script-security 2'
    state: present

- name: Ensure openvpn reloads /etc/resolve.conf on tun0 down
  ansible.builtin.lineinfile:
    path: /etc/openvpn/vpn.conf
    line: 'down /etc/openvpn/update-resolv-conf'
    insertafter: 'up /etc/openvpn/update-resolv-conf'
    state: present
