---
- name: Ensure ddns-update-style
  ansible.builtin.lineinfile:
    path: /etc/dhcp/dhcpd.conf
    regexp: '^#ddns-update-style none;'
    line: 'ddns-update-style none;'
    state: present

- name: Ensure authoritative status
  ansible.builtin.lineinfile:
    path: /etc/dhcp/dhcpd.conf
    regexp: '^#authoritative;'
    line: 'authoritative;'
    state: present

- name: Ensure dhcp scope is present
  ansible.builtin.lineinfile:
    path: /etc/dhcp/dhcpd.conf
    line: |
          subnet 172.16.35.0 netmask 255.255.255.0 {
          range 172.16.35.100 172.16.35.120;
          option broadcast-address 172.16.35.255;
          option routers 172.16.35.1;
          default-lease-time 600;
          max-lease-time 7200;
          option domain-name-servers 1.1.1.1;
          }
    state: present

- name: Ensure dhcp interface is set to br0
  ansible.builtin.lineinfile:
    path: /etc/default/isc-dhcp-server
    regexp: '^INTERFACESv4=""'
    line: 'INTERFACESv4="br0"'
    state: present
