---
lan_ssid: |
  interface=wlan1
  bridge=br0
  driver=nl80211
  # country_code=US
  ssid="{{ lan_ssid }}"
  hw_mode=a
  channel=48
  #ieee80211d=1
  ieee80211n=1
  ieee80211ac=1
  wmm_enabled=0
  macaddr_acl=0
  auth_algs=1
  ignore_broadcast_ssid=0
  wpa=2
  wpa_passphrase="{{ lan_pass_phrase }}"
  wpa_key_mgmt=WPA-PSK
  wpa_pairwise=TKIP
  rsn_pairwise=CCMP
