---
- name: Ensure home guest network is present
  ansible.builtin.lineinfile:
    path: /etc/hostapd/hostapd.conf
    line: "{{ lan_ssid }}"
    owner: root
    mode: 0644
    create: true
    state: present

- name: Ensure hostapd default config location is set
  ansible.builtin.lineinfile:
    path: /etc/default/hostapd
    regexp: '^DAEMON_CONF=""'
    line: 'DAEMON_CONF="/etc/hostapd/hostapd.conf"'
    state: present
