---
- name: Ensure country code is set
  ansible.builtin.lineinfile:
    path: /etc/wpa_supplicant/wpa_supplicant-wlan0.conf
    line: 'country=US'
    owner: root
    mode: 0644
    create: true
    state: present

- name: Generates encoded wpa passphrase
  ansible.builtin.shell:
    cmd: wpa_passphrase {{ wan_ssid }} {{ wan_pass_phrase }}
  args:
    executable: /bin/bash
  register: passphrase
  changed_when: (passphrase.stdout)

- name: Ensure wifi network info exists in wlan0 config
  ansible.builtin.lineinfile:
    path: /etc/wpa_supplicant/wpa_supplicant-wlan0.conf
    line: '{{ passphrase.stdout }}'
    state: present

- name: Ensure clear text passphrase is absent
  ansible.builtin.lineinfile:
    path: /etc/wpa_supplicant/wpa_supplicant-wlan0.conf
    regexp: '{{ wan_pass_phrase }}'
    line: ''
    state: absent

- name: Ensure wpa_supplicant.conf country code is set
  ansible.builtin.lineinfile:
    path: /etc/wpa_supplicant/wpa_supplicant.conf
    line: 'country=US'
    owner: root
    mode: 0644
    create: true
    state: present
